// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NineChronicles.DataProvider.Store;

#nullable disable

namespace NineChronicles.DataProvider.Executable.Migrations
{
    [DbContext(typeof(NineChroniclesContext))]
    [Migration("20220804040446_AddHackAndSlashSweep")]
    partial class AddHackAndSlashSweep
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.AbilityRankingModel", b =>
                {
                    b.Property<string>("AgentAddress")
                        .HasColumnType("longtext");

                    b.Property<int?>("ArmorId")
                        .HasColumnType("int");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("longtext");

                    b.Property<int?>("AvatarLevel")
                        .HasColumnType("int");

                    b.Property<int?>("Cp")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.Property<int?>("TitleId")
                        .HasColumnType("int");

                    b.ToTable("AbilityRanking");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.AgentModel", b =>
                {
                    b.Property<string>("Address")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Address");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.AvatarModel", b =>
                {
                    b.Property<string>("Address")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ArmorId")
                        .HasColumnType("int");

                    b.Property<int?>("AvatarLevel")
                        .HasColumnType("int");

                    b.Property<int?>("Cp")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("TitleId")
                        .HasColumnType("int");

                    b.HasKey("Address");

                    b.HasIndex("AgentAddress");

                    b.ToTable("Avatars");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.BattleArenaModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AvatarLevel")
                        .HasColumnType("int");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<decimal>("BurntNCG")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ChampionshipId")
                        .HasColumnType("int");

                    b.Property<string>("EnemyAvatarAddress")
                        .HasColumnType("longtext");

                    b.Property<int>("MedalCount")
                        .HasColumnType("int");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<int>("TicketCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Victory")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("AgentAddress");

                    b.HasIndex("AvatarAddress");

                    b.ToTable("BattleArenas");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.BattleArenaRankingModel", b =>
                {
                    b.Property<long>("AdditionalTicketPrice")
                        .HasColumnType("bigint");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("ArenaType")
                        .HasColumnType("longtext");

                    b.Property<int?>("ArmorId")
                        .HasColumnType("int");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("longtext");

                    b.Property<int>("AvatarLevel")
                        .HasColumnType("int");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<int>("ChampionshipId")
                        .HasColumnType("int");

                    b.Property<int?>("Cp")
                        .HasColumnType("int");

                    b.Property<long>("EndBlockIndex")
                        .HasColumnType("bigint");

                    b.Property<long>("EntranceFee")
                        .HasColumnType("bigint");

                    b.Property<int>("LossCount")
                        .HasColumnType("int");

                    b.Property<int>("MedalCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("PurchasedTicketCount")
                        .HasColumnType("int");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.Property<int>("RequiredMedalCount")
                        .HasColumnType("int");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<long>("StartBlockIndex")
                        .HasColumnType("bigint");

                    b.Property<int>("Ticket")
                        .HasColumnType("int");

                    b.Property<long>("TicketPrice")
                        .HasColumnType("bigint");

                    b.Property<int>("TicketResetCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("TitleId")
                        .HasColumnType("int");

                    b.Property<int>("WinCount")
                        .HasColumnType("int");

                    b.ToTable("BattleArenaRanking");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.BlockModel", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("Difficulty")
                        .HasColumnType("bigint");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<string>("Miner")
                        .HasColumnType("longtext");

                    b.Property<string>("Nonce")
                        .HasColumnType("longtext");

                    b.Property<string>("PreviousHash")
                        .HasColumnType("longtext");

                    b.Property<int?>("ProtocolVersion")
                        .HasColumnType("int");

                    b.Property<string>("PublicKey")
                        .HasColumnType("longtext");

                    b.Property<string>("StateRootHash")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("TotalDifficulty")
                        .HasColumnType("bigint");

                    b.Property<int?>("TxCount")
                        .HasColumnType("int");

                    b.Property<string>("TxHash")
                        .HasColumnType("longtext");

                    b.HasKey("Hash");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.ClaimStakeRewardModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ApPotionCount")
                        .HasColumnType("int");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("ClaimRewardAvatarAddress")
                        .HasColumnType("longtext");

                    b.Property<long>("ClaimStakeEndBlockIndex")
                        .HasColumnType("bigint");

                    b.Property<long>("ClaimStakeStartBlockIndex")
                        .HasColumnType("bigint");

                    b.Property<int>("HourGlassCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AgentAddress");

                    b.ToTable("ClaimStakeRewards");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.CombinationConsumableModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentAddress");

                    b.HasIndex("AvatarAddress");

                    b.ToTable("CombinationConsumables");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.CombinationEquipmentModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("int");

                    b.Property<int?>("SubRecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentAddress");

                    b.HasIndex("AvatarAddress");

                    b.ToTable("CombinationEquipments");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.CraftRankingInputModel", b =>
                {
                    b.Property<string>("AvatarAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("longtext");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<int>("CraftCount")
                        .HasColumnType("int");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.HasKey("AvatarAddress");

                    b.ToTable("CraftRankings");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.CraftRankingOutputModel", b =>
                {
                    b.Property<string>("AgentAddress")
                        .HasColumnType("longtext");

                    b.Property<int?>("ArmorId")
                        .HasColumnType("int");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("longtext");

                    b.Property<int?>("AvatarLevel")
                        .HasColumnType("int");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<int?>("Cp")
                        .HasColumnType("int");

                    b.Property<int>("CraftCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.Property<int?>("TitleId")
                        .HasColumnType("int");

                    b.ToTable("CraftRankingsOutput");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.EquipmentModel", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("longtext");

                    b.Property<int>("Cp")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<string>("ItemSubType")
                        .HasColumnType("longtext");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.EquipmentRankingModel", b =>
                {
                    b.Property<string>("AgentAddress")
                        .HasColumnType("longtext");

                    b.Property<int?>("ArmorId")
                        .HasColumnType("int");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("longtext");

                    b.Property<int?>("AvatarLevel")
                        .HasColumnType("int");

                    b.Property<int>("Cp")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<string>("ItemId")
                        .HasColumnType("longtext");

                    b.Property<string>("ItemSubType")
                        .HasColumnType("longtext");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.Property<int?>("TitleId")
                        .HasColumnType("int");

                    b.ToTable("EquipmentRanking");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.GrindingModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Crystal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<string>("EquipmentItemId")
                        .HasColumnType("longtext");

                    b.Property<int>("EquipmentLevel")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AgentAddress");

                    b.HasIndex("AvatarAddress");

                    b.ToTable("Grindings");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.HackAndSlashModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<bool>("Cleared")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Mimisbrunnr")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentAddress");

                    b.HasIndex("AvatarAddress");

                    b.ToTable("HackAndSlashes");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.HackAndSlashSweepModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ActionPoint")
                        .HasColumnType("int");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ApStoneCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<bool>("Cleared")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CostumesCount")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentsCount")
                        .HasColumnType("int");

                    b.Property<bool>("Mimisbrunnr")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WorldId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentAddress");

                    b.HasIndex("AvatarAddress");

                    b.ToTable("HackAndSlashSweeps");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.HasRandomBuffModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<decimal>("BurntCrystal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("GachaCount")
                        .HasColumnType("int");

                    b.Property<int>("HasStageId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AgentAddress");

                    b.HasIndex("AvatarAddress");

                    b.ToTable("HasRandomBuffs");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.HasWithRandomBuffModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<int>("BuffId")
                        .HasColumnType("int");

                    b.Property<bool>("Cleared")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AgentAddress");

                    b.HasIndex("AvatarAddress");

                    b.ToTable("HasWithRandomBuffs");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.ItemEnhancementFailModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<decimal>("BurntNCG")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("EquipmentItemId")
                        .HasColumnType("longtext");

                    b.Property<int>("EquipmentLevel")
                        .HasColumnType("int");

                    b.Property<decimal>("GainedCrystal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("MaterialItemId")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AgentAddress");

                    b.HasIndex("AvatarAddress");

                    b.ToTable("ItemEnhancementFails");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.ItemEnhancementModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("ItemId")
                        .HasColumnType("longtext");

                    b.Property<string>("MaterialId")
                        .HasColumnType("longtext");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentAddress");

                    b.HasIndex("AvatarAddress");

                    b.ToTable("ItemEnhancements");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.JoinArenaModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ArenaRound")
                        .HasColumnType("int");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AvatarLevel")
                        .HasColumnType("int");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<decimal>("BurntCrystal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ChampionshipId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AgentAddress");

                    b.HasIndex("AvatarAddress");

                    b.ToTable("JoinArenas");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.MigrateMonsterCollectionModel", b =>
                {
                    b.Property<string>("AgentAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AgentAddress1")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MigrationAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long>("MigrationStartBlockIndex")
                        .HasColumnType("bigint");

                    b.Property<long>("StakeStartBlockIndex")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("AgentAddress");

                    b.HasIndex("AgentAddress1");

                    b.ToTable("MigrateMonsterCollections");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.ReplaceCombinationEquipmentMaterialModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<decimal>("BurntCrystal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ReplacedMaterialCount")
                        .HasColumnType("int");

                    b.Property<int>("ReplacedMaterialId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AgentAddress");

                    b.HasIndex("AvatarAddress");

                    b.ToTable("ReplaceCombinationEquipmentMaterials");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.ShopConsumableModel", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<int>("BuffSkillCount")
                        .HasColumnType("int");

                    b.Property<int>("CombatPoint")
                        .HasColumnType("int");

                    b.Property<string>("ElementalType")
                        .HasColumnType("longtext");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<string>("ItemSubType")
                        .HasColumnType("longtext");

                    b.Property<string>("ItemType")
                        .HasColumnType("longtext");

                    b.Property<string>("MainStat")
                        .HasColumnType("longtext");

                    b.Property<string>("NonFungibleId")
                        .HasColumnType("longtext");

                    b.Property<string>("OrderId")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long>("RequiredBlockIndex")
                        .HasColumnType("bigint");

                    b.Property<long>("SellExpiredBlockIndex")
                        .HasColumnType("bigint");

                    b.Property<long>("SellStartedBlockIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("SellerAgentAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("SellerAvatarAddress")
                        .HasColumnType("longtext");

                    b.Property<int>("SkillsCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TradableId")
                        .HasColumnType("longtext");

                    b.HasKey("ItemId");

                    b.ToTable("ShopConsumables");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.ShopCostumeModel", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<int>("CombatPoint")
                        .HasColumnType("int");

                    b.Property<string>("ElementalType")
                        .HasColumnType("longtext");

                    b.Property<bool>("Equipped")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<string>("ItemSubType")
                        .HasColumnType("longtext");

                    b.Property<string>("ItemType")
                        .HasColumnType("longtext");

                    b.Property<string>("NonFungibleId")
                        .HasColumnType("longtext");

                    b.Property<string>("OrderId")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long>("RequiredBlockIndex")
                        .HasColumnType("bigint");

                    b.Property<long>("SellExpiredBlockIndex")
                        .HasColumnType("bigint");

                    b.Property<long>("SellStartedBlockIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("SellerAgentAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("SellerAvatarAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("SpineResourcePath")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TradableId")
                        .HasColumnType("longtext");

                    b.HasKey("ItemId");

                    b.ToTable("ShopCostumes");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.ShopEquipmentModel", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<int>("BuffSkillCount")
                        .HasColumnType("int");

                    b.Property<int>("CombatPoint")
                        .HasColumnType("int");

                    b.Property<string>("ElementalType")
                        .HasColumnType("longtext");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<string>("ItemSubType")
                        .HasColumnType("longtext");

                    b.Property<string>("ItemType")
                        .HasColumnType("longtext");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("NonFungibleId")
                        .HasColumnType("longtext");

                    b.Property<string>("OrderId")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long>("RequiredBlockIndex")
                        .HasColumnType("bigint");

                    b.Property<long>("SellExpiredBlockIndex")
                        .HasColumnType("bigint");

                    b.Property<long>("SellStartedBlockIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("SellerAgentAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("SellerAvatarAddress")
                        .HasColumnType("longtext");

                    b.Property<int>("SetId")
                        .HasColumnType("int");

                    b.Property<int>("SkillsCount")
                        .HasColumnType("int");

                    b.Property<string>("SpineResourcePath")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TradableId")
                        .HasColumnType("longtext");

                    b.Property<string>("UniqueStatType")
                        .HasColumnType("longtext");

                    b.HasKey("ItemId");

                    b.ToTable("ShopEquipments");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.ShopHistoryConsumableModel", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BlockHash")
                        .HasColumnType("longtext");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<int>("BuffSkillCount")
                        .HasColumnType("int");

                    b.Property<string>("BuyerAvatarAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("ElementalType")
                        .HasColumnType("longtext");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<string>("ItemId")
                        .HasColumnType("longtext");

                    b.Property<string>("ItemSubType")
                        .HasColumnType("longtext");

                    b.Property<string>("ItemType")
                        .HasColumnType("longtext");

                    b.Property<string>("MainStat")
                        .HasColumnType("longtext");

                    b.Property<string>("NonFungibleId")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long>("RequiredBlockIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("SellerAvatarAddress")
                        .HasColumnType("longtext");

                    b.Property<int>("SkillsCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TradableId")
                        .HasColumnType("longtext");

                    b.Property<string>("TxId")
                        .HasColumnType("longtext");

                    b.HasKey("OrderId");

                    b.ToTable("ShopHistoryConsumables");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.ShopHistoryCostumeModel", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BlockHash")
                        .HasColumnType("longtext");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("BuyerAvatarAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("ElementalType")
                        .HasColumnType("longtext");

                    b.Property<bool>("Equipped")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<string>("ItemId")
                        .HasColumnType("longtext");

                    b.Property<string>("ItemSubType")
                        .HasColumnType("longtext");

                    b.Property<string>("ItemType")
                        .HasColumnType("longtext");

                    b.Property<string>("NonFungibleId")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long>("RequiredBlockIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("SellerAvatarAddress")
                        .HasColumnType("longtext");

                    b.Property<int>("SetId")
                        .HasColumnType("int");

                    b.Property<string>("SpineResourcePath")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TradableId")
                        .HasColumnType("longtext");

                    b.Property<string>("TxId")
                        .HasColumnType("longtext");

                    b.HasKey("OrderId");

                    b.ToTable("ShopHistoryCostumes");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.ShopHistoryEquipmentModel", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BlockHash")
                        .HasColumnType("longtext");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<int>("BuffSkillCount")
                        .HasColumnType("int");

                    b.Property<string>("BuyerAvatarAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("ElementalType")
                        .HasColumnType("longtext");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<string>("ItemId")
                        .HasColumnType("longtext");

                    b.Property<string>("ItemSubType")
                        .HasColumnType("longtext");

                    b.Property<string>("ItemType")
                        .HasColumnType("longtext");

                    b.Property<string>("NonFungibleId")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long>("RequiredBlockIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("SellerAvatarAddress")
                        .HasColumnType("longtext");

                    b.Property<int>("SetId")
                        .HasColumnType("int");

                    b.Property<int>("SkillsCount")
                        .HasColumnType("int");

                    b.Property<string>("SpineResourcePath")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TradableId")
                        .HasColumnType("longtext");

                    b.Property<string>("TxId")
                        .HasColumnType("longtext");

                    b.Property<string>("UniqueStatType")
                        .HasColumnType("longtext");

                    b.HasKey("OrderId");

                    b.ToTable("ShopHistoryEquipments");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.ShopHistoryMaterialModel", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BlockHash")
                        .HasColumnType("longtext");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("BuyerAvatarAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("ElementalType")
                        .HasColumnType("longtext");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<string>("ItemId")
                        .HasColumnType("longtext");

                    b.Property<string>("ItemSubType")
                        .HasColumnType("longtext");

                    b.Property<string>("ItemType")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SellerAvatarAddress")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TxId")
                        .HasColumnType("longtext");

                    b.HasKey("OrderId");

                    b.ToTable("ShopHistoryMaterials");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.ShopMaterialModel", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<int>("CombatPoint")
                        .HasColumnType("int");

                    b.Property<string>("ElementalType")
                        .HasColumnType("longtext");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<string>("ItemSubType")
                        .HasColumnType("longtext");

                    b.Property<string>("ItemType")
                        .HasColumnType("longtext");

                    b.Property<string>("OrderId")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long>("SellExpiredBlockIndex")
                        .HasColumnType("bigint");

                    b.Property<long>("SellStartedBlockIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("SellerAgentAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("SellerAvatarAddress")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TradableId")
                        .HasColumnType("longtext");

                    b.HasKey("ItemId");

                    b.ToTable("ShopMaterials");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.StageRankingModel", b =>
                {
                    b.Property<string>("AgentAddress")
                        .HasColumnType("longtext");

                    b.Property<int?>("ArmorId")
                        .HasColumnType("int");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("longtext");

                    b.Property<int?>("AvatarLevel")
                        .HasColumnType("int");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<int>("ClearedStageId")
                        .HasColumnType("int");

                    b.Property<int?>("Cp")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.Property<int?>("TitleId")
                        .HasColumnType("int");

                    b.ToTable("StageRanking");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.StakeModel", b =>
                {
                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<decimal>("NewAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long>("NewStakeStartBlockIndex")
                        .HasColumnType("bigint");

                    b.Property<long>("PrevStakeStartBlockIndex")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PreviousAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("RemainingNCG")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("TimeStamp");

                    b.HasIndex("AgentAddress");

                    b.ToTable("Stakings");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.TransactionModel", b =>
                {
                    b.Property<string>("TxId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ActionType")
                        .HasColumnType("longtext");

                    b.Property<string>("BlockHash")
                        .HasColumnType("longtext");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("Nonce")
                        .HasColumnType("bigint");

                    b.Property<string>("PublicKey")
                        .HasColumnType("longtext");

                    b.Property<string>("Signer")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedAddressesCount")
                        .HasColumnType("int");

                    b.HasKey("TxId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.UnlockEquipmentRecipeModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<decimal>("BurntCrystal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UnlockEquipmentRecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentAddress");

                    b.HasIndex("AvatarAddress");

                    b.ToTable("UnlockEquipmentRecipes");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.UnlockWorldModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("bigint");

                    b.Property<decimal>("BurntCrystal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UnlockWorldId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentAddress");

                    b.HasIndex("AvatarAddress");

                    b.ToTable("UnlockWorlds");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.AvatarModel", b =>
                {
                    b.HasOne("NineChronicles.DataProvider.Store.Models.AgentModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentAddress");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.BattleArenaModel", b =>
                {
                    b.HasOne("NineChronicles.DataProvider.Store.Models.AgentModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentAddress");

                    b.HasOne("NineChronicles.DataProvider.Store.Models.AvatarModel", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarAddress");

                    b.Navigation("Agent");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.ClaimStakeRewardModel", b =>
                {
                    b.HasOne("NineChronicles.DataProvider.Store.Models.AgentModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentAddress");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.CombinationConsumableModel", b =>
                {
                    b.HasOne("NineChronicles.DataProvider.Store.Models.AgentModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentAddress");

                    b.HasOne("NineChronicles.DataProvider.Store.Models.AvatarModel", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarAddress");

                    b.Navigation("Agent");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.CombinationEquipmentModel", b =>
                {
                    b.HasOne("NineChronicles.DataProvider.Store.Models.AgentModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentAddress");

                    b.HasOne("NineChronicles.DataProvider.Store.Models.AvatarModel", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarAddress");

                    b.Navigation("Agent");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.GrindingModel", b =>
                {
                    b.HasOne("NineChronicles.DataProvider.Store.Models.AgentModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentAddress");

                    b.HasOne("NineChronicles.DataProvider.Store.Models.AvatarModel", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarAddress");

                    b.Navigation("Agent");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.HackAndSlashModel", b =>
                {
                    b.HasOne("NineChronicles.DataProvider.Store.Models.AgentModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentAddress");

                    b.HasOne("NineChronicles.DataProvider.Store.Models.AvatarModel", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarAddress");

                    b.Navigation("Agent");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.HackAndSlashSweepModel", b =>
                {
                    b.HasOne("NineChronicles.DataProvider.Store.Models.AgentModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentAddress");

                    b.HasOne("NineChronicles.DataProvider.Store.Models.AvatarModel", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarAddress");

                    b.Navigation("Agent");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.HasRandomBuffModel", b =>
                {
                    b.HasOne("NineChronicles.DataProvider.Store.Models.AgentModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentAddress");

                    b.HasOne("NineChronicles.DataProvider.Store.Models.AvatarModel", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarAddress");

                    b.Navigation("Agent");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.HasWithRandomBuffModel", b =>
                {
                    b.HasOne("NineChronicles.DataProvider.Store.Models.AgentModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentAddress");

                    b.HasOne("NineChronicles.DataProvider.Store.Models.AvatarModel", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarAddress");

                    b.Navigation("Agent");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.ItemEnhancementFailModel", b =>
                {
                    b.HasOne("NineChronicles.DataProvider.Store.Models.AgentModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentAddress");

                    b.HasOne("NineChronicles.DataProvider.Store.Models.AvatarModel", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarAddress");

                    b.Navigation("Agent");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.ItemEnhancementModel", b =>
                {
                    b.HasOne("NineChronicles.DataProvider.Store.Models.AgentModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentAddress");

                    b.HasOne("NineChronicles.DataProvider.Store.Models.AvatarModel", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarAddress");

                    b.Navigation("Agent");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.JoinArenaModel", b =>
                {
                    b.HasOne("NineChronicles.DataProvider.Store.Models.AgentModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentAddress");

                    b.HasOne("NineChronicles.DataProvider.Store.Models.AvatarModel", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarAddress");

                    b.Navigation("Agent");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.MigrateMonsterCollectionModel", b =>
                {
                    b.HasOne("NineChronicles.DataProvider.Store.Models.AgentModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentAddress1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.ReplaceCombinationEquipmentMaterialModel", b =>
                {
                    b.HasOne("NineChronicles.DataProvider.Store.Models.AgentModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentAddress");

                    b.HasOne("NineChronicles.DataProvider.Store.Models.AvatarModel", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarAddress");

                    b.Navigation("Agent");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.StakeModel", b =>
                {
                    b.HasOne("NineChronicles.DataProvider.Store.Models.AgentModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentAddress");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.UnlockEquipmentRecipeModel", b =>
                {
                    b.HasOne("NineChronicles.DataProvider.Store.Models.AgentModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentAddress");

                    b.HasOne("NineChronicles.DataProvider.Store.Models.AvatarModel", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarAddress");

                    b.Navigation("Agent");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.UnlockWorldModel", b =>
                {
                    b.HasOne("NineChronicles.DataProvider.Store.Models.AgentModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentAddress");

                    b.HasOne("NineChronicles.DataProvider.Store.Models.AvatarModel", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarAddress");

                    b.Navigation("Agent");

                    b.Navigation("Avatar");
                });
#pragma warning restore 612, 618
        }
    }
}
