// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NineChronicles.DataProvider.Store;

namespace NineChronicles.DataProvider.Executable.Migrations
{
    [DbContext(typeof(NineChroniclesContext))]
    partial class NineChroniclesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.AgentModel", b =>
                {
                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.HasKey("Address");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.AvatarModel", b =>
                {
                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Address");

                    b.HasIndex("AgentAddress");

                    b.ToTable("Avatars");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.CombinationConsumableModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("TEXT");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentAddress");

                    b.HasIndex("AvatarAddress");

                    b.ToTable("CombinationConsumables");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.CombinationEquipmentModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("TEXT");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubRecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentAddress");

                    b.HasIndex("AvatarAddress");

                    b.ToTable("CombinationEquipments");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.CraftRankingModel", b =>
                {
                    b.Property<string>("AvatarAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("TEXT");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CraftCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ranking")
                        .HasColumnType("INTEGER");

                    b.HasKey("AvatarAddress");

                    b.ToTable("CraftRankings");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.HackAndSlashModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("TEXT");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cleared")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Mimisbrunnr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentAddress");

                    b.HasIndex("AvatarAddress");

                    b.ToTable("HackAndSlashes");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.ItemEnhancementModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("TEXT");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentAddress");

                    b.HasIndex("AvatarAddress");

                    b.ToTable("ItemEnhancements");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.StageRankingModel", b =>
                {
                    b.Property<int>("Ranking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarAddress")
                        .HasColumnType("TEXT");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClearedStageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Ranking");

                    b.ToTable("StageRankings");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.AvatarModel", b =>
                {
                    b.HasOne("NineChronicles.DataProvider.Store.Models.AgentModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentAddress");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.CombinationConsumableModel", b =>
                {
                    b.HasOne("NineChronicles.DataProvider.Store.Models.AgentModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentAddress");

                    b.HasOne("NineChronicles.DataProvider.Store.Models.AvatarModel", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarAddress");

                    b.Navigation("Agent");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.CombinationEquipmentModel", b =>
                {
                    b.HasOne("NineChronicles.DataProvider.Store.Models.AgentModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentAddress");

                    b.HasOne("NineChronicles.DataProvider.Store.Models.AvatarModel", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarAddress");

                    b.Navigation("Agent");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.HackAndSlashModel", b =>
                {
                    b.HasOne("NineChronicles.DataProvider.Store.Models.AgentModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentAddress");

                    b.HasOne("NineChronicles.DataProvider.Store.Models.AvatarModel", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarAddress");

                    b.Navigation("Agent");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("NineChronicles.DataProvider.Store.Models.ItemEnhancementModel", b =>
                {
                    b.HasOne("NineChronicles.DataProvider.Store.Models.AgentModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentAddress");

                    b.HasOne("NineChronicles.DataProvider.Store.Models.AvatarModel", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarAddress");

                    b.Navigation("Agent");

                    b.Navigation("Avatar");
                });
#pragma warning restore 612, 618
        }
    }
}
